* update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,21 +32,26 @@ qmake_qt4="`which qmake-qt4`"
 tmp_qmake=""
 
 if [ "$qmake" = "" ]; then
-    echo "not found!"
-    echo
-    echo "Make sure you have the Qt development packages installed!"
-    exit 1
+	if [ "$qmake_qt4" = "" ]; then
+		echo "not found!"
+		echo
+		echo "Make sure you have the Qt development packages installed!"
+		exit 1
+	else
+		tmp_qmake=$qmake_qt4
+		echo $tmp_qmake
+	fi
 elif [ "$qmake_qt4" = "" ]; then
-    echo "not found!"
-    echo
-    echo "Make sure you have the Qt development packages installed!"
-    exit 1
+	echo "not found!"
+	echo
+	echo "Make sure you have the Qt development packages installed!"
+	exit 1
 else
 	if [ "$qmake" != "" ]; then
 		tmp_qmake=$qmake
 		echo $tmp_qmake
 	elif [ "$qmake_qt4" != "" ]; then
-		tmp_qmake=$qmake_qt4
+		tmp_qmake=$qmake
 		echo $tmp_qmake
 	fi
 fi
@@ -80,7 +85,7 @@ fi
 printf "Checking for lrelease... "
 lrelease_qt4="`which lrelease-qt4`"
 lrelease="`which lrelease`"
-tmp_lrelease="" 
+tmp_lrelease=""
 
 if [ "$lrelease" = "" ]; then
 	echo "not found!"
